### PR TITLE
Add support for addition of Multiple Host Domains to K8s Ingress Rules

### PR DESCRIPTION
**Pull request by unknownstring**
Include Host name in Yarp Route Id, when parsing Ingress Manifest Rules.

Fixes issue as described in #1950

### CODE REVIEW

**Comment by unknownstring** [comment]
>

**Comment by unknownstring** [comment]
@microsoft-github-policy-service agree company="GN Audio A/S"

**Comment by MihaZupan** [comment]
Thanks for looking to contribute here!

> Our Nginx rules are 'project' based, hence we use subdomains to organize and target individual related services.

> Due to Ingress manifest parsing and Yarp route id naming, this is not currently possible.

> Hence, suggestion is to include host domain as part of the route naming. This reduces duplicating Ingress manifests and additionally bundles related host domains in Azure Ingress overview.

Can you elaborate on how including the host into the route id simplifies this for you?

This `RouteId` is only visible internally to the YARP process. Are you using custom middleware to react to this ID?

**Comment by unknownstring** [comment]
> Thanks for looking to contribute here!
> 
> > Our Nginx rules are 'project' based, hence we use subdomains to organize and target individual related services.
> 
> > Due to Ingress manifest parsing and Yarp route id naming, this is not currently possible.
> 
> > Hence, suggestion is to include host domain as part of the route naming. This reduces duplicating Ingress manifests and additionally bundles related host domains in Azure Ingress overview.
> 
> Can you elaborate on how including the host into the route id simplifies this for you?
> 
> This `RouteId` is only visible internally to the YARP process. Are you using custom middleware to react to this ID?

Hi!

it's more a question of duplicate RouteIds and less about visibility. 

In the current implementation, adding multiple hosts to rules for a given Ingress parses duplicate RouteIds to YARP, as RouteId is based on _Ingress name and path only_. 

Hence the deployment of Ingress to K8s fails during validation.

**Comment by dpetrovych** [comment]
Hi @MihaZupan , I'm co-authoring this change.
We are not using RouteId in any way. By including `{host}` we want to avoid `RouteId` duplicates when using quite standard and valid k8s configuration for [Name based virtual hosting](https://kubernetes.io/docs/concepts/services-networking/ingress/#name-based-virtual-hosting).

So, in the test example _test/Kubernetes.Tests/testassets/multiple-hosts/routes.json_ before change all routes would have `RouteId: repro-1-ingress.foo:/`, this won't pass validation in https://github.com/microsoft/reverse-proxy/blob/9253842eea4b702489c9e4559a98f9d04d52c853/src/ReverseProxy/Management/ProxyConfigManager.cs#L373

Same error we first faced in one of k8s deployments:
image

**Comment by MihaZupan** [comment]
Thank you for the explanation, that makes sense.

**Review by MihaZupan — APPROVED** [review]

**Pull request merged**
