### PR TITLE
Upload test logs

### PR DESCRIPTION
**Pull request by Tratcher**
I'm trying to debug a test failure in https://github.com/microsoft/reverse-proxy/pull/168 and found that the test logs are not being uploaded.

### CODE REVIEW

**Comment by Tratcher** [comment]
Nevermind, I finally found them.

**Comment by halter73** [comment]
Were you looking for Microsoft.ReverseProxy.Tests_netcoreapp3.1_x64.log from https://dev.azure.com/dnceng/public/_build/results?buildId=647030&view=results? If so, where did you find it?

Also, it looks like the following line in our job template is broken:

https://github.com/microsoft/reverse-proxy/blob/f12c9eacf954f3d5d5cd15d8912841ead06ceabf/eng/common/templates/job/job.yml#L29

image

Not sure why or what the fix is though.

**Comment by Tratcher** [comment]
image

**Comment by anurse** [comment]
> Not sure why or what the fix is though.

https://github.com/dotnet/arcade/pull/5171

**Comment by halter73** [comment]
Approved!

**Pull request closed without merging**
