### PR TITLE
Make StructuredTransformer public

### PR DESCRIPTION
**Pull request by leastprivilege**
As discussed here #801

### CODE REVIEW

**Comment by Tratcher** [comment]
While making StructuredTransformer public is sufficient short term, its user experience for creating the transforms is still pretty bad right?

What about the proposal from the issue?
```
            var transformBuilder = app.ApplicationServices.GetRequiredService<ITransformBuilder>();
            var transforms = transformBuilder.Create(transformBuilderContext =>
            {
                transformBuilderContext.AddXForwarded();
            });
```

We already have all those types and extensions, only the Create method would be new. I bring it up here because this proposal wouldn't use a public StructuredTransformer and I'd like to avoid a stopgap if possible.

**Comment by leastprivilege** [comment]
What would `Create` return?

**Comment by Tratcher** [comment]
The base type HttpTransformer.

**Comment by alnikola** [comment]
There is now a related PR #913 introducing the `Create` method discussed above.

**Comment by Tratcher** [comment]
Replaced by #913. @leastprivilege give that a try and let us know what you think.

**Comment by leastprivilege** [comment]
Cool thanks!

Is there an ETA for the next preview?

**Comment by Tratcher** [comment]
Nothing specific, though we are about due for our monthly preview. You can try the daily builds in the meantime:
https://github.com/microsoft/reverse-proxy/blob/main/docs/DailyBuilds.md

**Pull request closed without merging**
