### PR TITLE
Update proxyhttpclientconfig.md

### PR DESCRIPTION
**Pull request by sleemer**
fix: DangerousAcceptAnyServerCertificate instead of ValidateRemoteCertificate.

### CODE REVIEW

**Review by alnikola — APPROVED** [review]
LGTM

**Comment by alnikola** [comment]
Thank you!

**Comment by alnikola** [comment]
Oh, I just realized that PR was created against incorrect branch! It should have been `master` not `release\docs`.

**Comment by alnikola** [comment]
I will revert it. Please, create a PR against 'master'.

**Comment by sleemer** [comment]
Will do

**Comment by Tratcher** [comment]
Hold up, we can merge this branch to master.

**Pull request merged**
