### PR TITLE
Add a non async path for transforms

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/microsoft/reverse-proxy/issues/663

### CODE REVIEW

**Comment by MihaZupan** [comment]
Did several runs, seems to be a measurable improvement of around 0.5 - 1 %.

**Comment by MihaZupan** [comment]
Could we reduce some code duplication by extracting the shared portion after `ShouldCopyRequestHeaders` into a separate method?

**Comment by Kahbazi** [comment]
> Could we reduce some code duplication by extracting the shared portion after `ShouldCopyRequestHeaders` into a separate method?

I'm not sure how to refactor it. The types are different, and each method is accessing a different property.

**Comment by Tratcher** [comment]
@MihaZupan did it help with allocations any?

**Comment by MihaZupan** [comment]
> did it help with allocations any?

No - since these methods never actually "go async", the state machines stay as structs and don't allocate.


Seeing as the performance difference is small (almost within the margin of error), I don't think it is worth duplicating all this logic.
Thank you for looking into this potential optimization @Kahbazi, but I don't think we'll be taking this change unless we see a bigger perf difference / find a way to avoid complicating the logic too much.

Did you by any chance run a microbenchmark for just the transformer to see a perf difference there?

**Comment by Kahbazi** [comment]
> Did you by any chance run a microbenchmark for just the transformer to see a perf difference there?

No. I will run one and post the result.

**Comment by Kahbazi** [comment]
Here's a benchmark of `TransformRequestAsync` with the default transformers which are removing the incoming host header and X-Forwarded headers.

|  Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
| Current | 3.210 us | 0.0450 us | 0.0399 us | 0.5684 |     - |     - |   1.74 KB |
|     New | 2.894 us | 0.0267 us | 0.0208 us | 0.5531 |     - |     - |    1.7 KB |

**Comment by samsp-msft** [comment]
Triage: Thank you for the effort, but based on the numbers we don't think this change is worth taking for the amount of complexity it introduces.

**Pull request closed without merging**
