### PR TITLE
Use Arcade's pool-providers.yml

### PR DESCRIPTION
**Pull request by dougbu**
- import the variable template
- use the two variables it provides wherever we name the pool
  - future release branches will now automatically switch to the -Svc pools

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
We froze the subscriptions because we were still building against .NET 7 and Arcade kept trying to push us to 8. We've released now, so it should be ok to re-enable the Arcade and runtime subscriptions.

**Review by Tratcher — APPROVED** [review]

**Comment by dougbu** [comment]
> We froze the subscriptions because we were still building against .NET 7 and Arcade kept trying to push us to 8. We've released now, so it should be ok to re-enable the Arcade and runtime subscriptions.

And the aspnetcore sub too❔

**Comment by Tratcher** [comment]
Sure, once the Arcade one goes through.

**Comment by dougbu** [comment]
Arcade update complete and all subscriptions are now reenabled. This should work now&hellip;

**Pull request merged**
