### PR TITLE
Update CredScan suppressions

### PR DESCRIPTION
**Pull request by MihaZupan**
Use config-based suppressions for all passwords in the flagged `.cs` files.

### CODE REVIEW

**Comment by Tratcher** [comment]
Any idea why the inline suppressions didn't work?

**Comment by ManickaP** [comment]
> Any idea why the inline suppressions didn't work?

Quoting CredScan: `NOTE: It is not enough to remove the secrets and push another change. You must reset your branch according to the instructions.`

It looks like it checks each of the pulled commits individually. We'd need to bypass it with a special commit. Or once it's there, we might try go back to inline suppression (the pulled change won't contain any secrets in any commits).

**Comment by MihaZupan** [comment]
My understanding is that we would have to remove them from history if we actually wanted to remove them. Here we've we're just telling CredScan that it's wrong in these cases.

**Review by Tratcher — APPROVED** [review]

**Comment by MihaZupan** [comment]
From what I see code-mirror is happy with this now

**Pull request merged**
