### PR TITLE
Use is null instead of == null

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/microsoft/reverse-proxy/issues/1552

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]
Is there an editorconfig / analyzer rule we can enforce to maintain this style in the future?

**Comment by redcinelli** [comment]
I might completely be out of line, but [ide0041](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0041) is the rule you are looking for.

I believe this should look like smth like that in the `.editorconfig`: 

```ini
#IDE0041
dotnet_style_prefer_is_null_check_over_reference_equality_method = true
```

**Comment by MihaZupan** [comment]
Sadly I believe that rule only applies to code like

```c#
if (ReferenceEquals(foo, null))
```
and not
```c#
if (foo == null)
```

**Comment by karelz** [comment]
Triage: There is not analyzer to track this, which is sad.
We will take this. Sorry for the delay @Kahbazi. Would you mind resolving the conflicts, so that we can merge?

Thanks!

**Pull request merged**
