### PR TITLE
Improvement some conditional statement

### PR DESCRIPTION
**Pull request by mokarchi**

### CODE REVIEW

**Review by MihaZupan — COMMENTED** [review]
Thank you for looking to contribute to the project, but can you elaborate on what the motivation behind this change is? I'm not sure it helps with readability.

**Comment by mokarchi** [comment]
I think so yes there is no behind motivation because if/else and switch is a code smell and specific part for refactoring code with strategy pattern or chain of responsibilty pattern but also use switch is simple way for extend source code and temporary treatment

**Comment by Tratcher** [comment]
FYI we don't normally accept style-only PRs as it is very subjective and doesn't improve the functionality of the product.

**Comment by mokarchi** [comment]
@Tratcher Should I Close PR?

**Pull request closed without merging**
