### PR TITLE
Packages referenced by YARP

### LINKED ISSUE #996: Package references and their licenses should be clearly documented
YARP itself does not reference other packages, but the Kubernetes ingress and some samples do. We should make sure that those are called out in the readme for each part, and that the licenses are listed.

Close compliance item [1272006](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1272006) when complete.

### PR DESCRIPTION
**Pull request by alnikola**
Fixes #996

### CODE REVIEW

**Comment by Tratcher** [comment]
"We should make sure that those are called out in the readme for each part" I don't think this was supposed to go into the conceptual docs, but rather into the project source code folders.

**Comment by samsp-msft** [comment]
I'm not opposed to having this as a top level document - In some ways the samples (where most of the breadth comes from) are self documenting in that they have the references listed.

Can this be converted into a table so it's easier to read, and grouped by project?

**Review by Tratcher — APPROVED** [review]

**Comment by Kahbazi** [comment]
@alnikola Does this also need to be added to [Table of Content](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/toc.yml)?

**Comment by alnikola** [comment]
@Kahbazi, good point. I will open a PR.

**Pull request merged**
