### PR TITLE
Add EnableMultipleHttp2Connections to ProxyHttpClientOptions

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/microsoft/reverse-proxy/issues/675

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Quick as usual, thanks 😁

**Comment by samsp-msft** [comment]
@MihaZupan - can you rerun the h2 perf tests now this is incorporated.

**Comment by MihaZupan** [comment]
Reran the tests and this was the reason for the h1 vs h2 difference.

Note: `-single` means without setting the `EnableMultipleHttp2Connections`

| load                   | `win-h2-https` | `win-h2-h2-single` |          | `win-h2-h2` |         |
| ---------------------- | ------------ | ---------------- | -------- | --------- | ------- |
| Mean latency (us)      |        4.782 |           13.805 | +188,71% |     4.867 |  +1,79% |
| Requests               |      797.972 |          276.323 |  -65,37% |   783.509 |  -1,81% |
| Requests/sec           |       54.362 |           18.717 |  -65,57% |    52.339 |  -3,72% |
| Requests/sec (max)     |       63.942 |           27.504 |  -56,99% |    72.236 | +12,97% |
| Read throughput (MB/s) |        13,72 |             4,76 |  -65,29% |     13,47 |  -1,81% |

| load                   | `lin-h2-https` | `lin-h2-h2-single` |          | `lin-h2-h2` |         |
| ---------------------- | ------------ | ---------------- | -------- | --------- | ------- |
| Mean latency (us)      |        4.066 |           14.913 | +266,81% |     6.326 | +55,59% |
| Requests/sec           |       62.974 |           17.165 |  -72,74% |    40.487 | -35,71% |
| Requests/sec (max)     |       70.212 |           31.087 |  -55,72% |    54.874 | -21,85% |
| Read throughput (MB/s) |        15,36 |             4,21 |  -72,58% |      9,89 | -35,61% |


While enabling `EnableMultipleHttp2Connections` for the benchmarks makes complete sense, should we just make multiple connections the default? @Tratcher @samsp-msft

**Comment by Tratcher** [comment]
EnableMultipleHttp2Connections wasn't enabled by default in HttpClient due to compatibility concerns, right? Is YARPs environment sufficiently different to avoid those?

**Comment by samsp-msft** [comment]
I think that was because we didn't know whether the server(s) would support multiple connections from the same client - its quite likely that will be blocked when facing the internet, but not for server to server or proxy to server scenarios.

I think we can enable by default for YARP.

**Comment by samsp-msft** [comment]
Based on the bolded below

| load                   | `lin-h2-https` | `lin-h2-h2-single` |          | `lin-h2-h2` |         |
| ---------------------- | ------------ | ---------------- | -------- | --------- | ------- |
| Mean latency (us)      |        4.066 |           14.913 | +266,81% |     6.326 | +55,59% |
| Requests               |      942.108 |          257.287 |  -72,69% |   606.141 | -35,66% |
| Requests/sec           |       **62.974** |           17.165 |  -72,74% |    **40.487** | -35,71% |
| Requests/sec (max)     |       70.212 |           31.087 |  -55,72% |    54.874 | -21,85% |
| Read throughput (MB/s) |        15,36 |             4,21 |  -72,58% |      9,89 | -35,61% |

It seems like there is still some discrepancy in the h2 implementation on Linux compared to https. This is not showing for the windows results. We should drill into this to find out why.

**Comment by MihaZupan** [comment]
Afaik the concern originally was that it's technically against the spec to open more than 1 HTTP/2 connection (as the server should just allow more streams).

**Comment by Tratcher** [comment]
I recall there were specific servers brought up that were known to reject multiple connections as a protocol violation, but I don't see that recorded in the original issue or PR.

At this point we can opt-in by default and see what feedback we get. It will be harder to opt-in by default later.

**Pull request merged**
