### PR TITLE
Update docfx to 2.58

### LINKED ISSUE #829: xref links from Articles to ref docs are not working.
### Describe the bug
x:ref links for example the ones to Cluster and Route in https://microsoft.github.io/reverse-proxy/articles/configfiles.html are not linking correctly.

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #829

### CODE REVIEW

**Review by alnikola — APPROVED** [review]
LGTM

**Comment by Tratcher** [comment]
Did you see if it helped with #1067?

**Review by Tratcher — APPROVED** [review]

**Comment by MihaZupan** [comment]
The build log is so noisy it's hard to tell

Build output before/after (you can see the diff but it's not that useful)
https://gist.github.com/MihaZupan/c8e6019d2db138b0fd2f0a3f84f71f65

I still see a bunch of `invalid cross reference` warnings Alexander mentioned

**Comment by Tratcher** [comment]
Some of those look like broken links that can be fixed. We should do a cleanup pass after the renames are done to make sure.

**Comment by MihaZupan** [comment]
We can look at all the warnings as part of #1067

**Pull request merged**
