### PR TITLE
Updating benchmarks certificate

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
This one is not expired. Will also match the certificate for other benchmarks.

**Comment by sebastienros** [comment]
However I am not even sure it's used anywhere. Where is it configured in yarp?

**Comment by Tratcher** [comment]
Here?
https://github.com/microsoft/reverse-proxy/blob/3bcabe79afc7687c05db35be077dc2e10283b959/testassets/BenchmarkApp/Program.cs#L23

**Comment by sebastienros** [comment]
@Tratcher thanks, I was looking in the startup and in the config.

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
