### PR TITLE
Update proxyhttpclientconfig.md (#626)

### PR DESCRIPTION
**Pull request by alnikola**
fix: DangerousAcceptAnyServerCertificate instead of ValidateRemoteCertificate.

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by alnikola** [comment]
Hmm, it automatically deleted `release/docs` branch for some reason. Is it OK?

**Comment by Tratcher** [comment]
Restore it. There's a rule that does that for all or branches merged to master. We should figure out how to suppress it for release branches.

**Comment by Tratcher** [comment]
I've added branch protection rules for `release/docs` similar to the ones on master. That suppressed the delete-branch button, so it might suppress the auto-delete branch as well.

**Comment by Tratcher** [comment]
Side note: remember to make merge commits (rather than squash-and-merge or rebase) when merging between long lived branches.

**Pull request merged**
