### PR TITLE
chore: fix prometheus sample metric typos in description

### PR DESCRIPTION
**Pull request by asafdl**

### CODE REVIEW

**Comment by asafdl** [comment]
@microsoft-github-policy-service agree [company="elementor"]

**Comment by adityamandaleeka** [comment]
Thanks @asafdl. Looks like the bot wants a slightly different syntax for the agreement.

**Review by adityamandaleeka — APPROVED** [review]
LGTM pending license agreement.

**Comment by asafdl** [comment]
@microsoft-github-policy-service agree company="elementor"

**Pull request merged**
